name: check_for_new_version

env:
  APPLICATION: keepalived

on:
  workflow_dispatch:  # allows for triggering workflow manually.
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check-version:
    runs-on:
      - gha-runner-scale-set-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to private # to pull (cached) base image
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_PRIVATE_PULL }}
          username: ${{ secrets.REGISTRY_PRIVATE_USER01 }}
          password: "${{ secrets.REGISTRY_PRIVATE_USER01_PASSWD }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=${{ vars.REGISTRY_PRIVATE_PULL }}/moby/buildkit:buildx-stable-1
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/docker/DockerfileVersion
          push: false
          load: true  # automatically loads the single-platform build result to docker images (for use in next step).
          cache-from: type=gha,scope=build-${{ env.APPLICATION }}-version-${{ runner.arch }}
          cache-to: type=gha,mode=max,scope=build-${{ env.APPLICATION }}-version-${{ runner.arch }}
          build-args: |
            REGISTRY=${{ vars.REGISTRY_PRIVATE_PULL }}
          tags: version-image:latest
      - name: Run container
        id: run-container
        run: |
          LATEST_VERSION=$(docker run --rm version-image:latest)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT
      - name: Update secrets
        run: |
          if [ "${{ steps.run-container.outputs.LATEST_VERSION }}" != "${{ vars.KEEPALIVED_VERSION }}" ]; then
            echo "Current version: ${{ vars.KEEPALIVED_VERSION }}"
            echo "Latest version: $LATEST_VERSION"
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_DEFAULT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"KEEPALIVED_VERSION\",\"value\":\"${{ steps.run-container.outputs.LATEST_VERSION }}\"}" \
              https://api.github.com/repos/v6Org01/keepalived/actions/variables/KEEPALIVED_VERSION
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_DEFAULT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"event_type\":\"trigger-wf-pushImage2Registry\"}" \
              https://api.github.com/repos/v6Org01/keepalived/dispatches
          else
            echo "No new version found."
          fi
