name: push_image_to_registry

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["keepalived.conf.env"]
  repository_dispatch:
    types: ["trigger-wf-pushImage2Registry"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  build-image-push:
    uses: v6Org01/.github/.github/workflows/BuildPushImage.yaml@main
    with:
      APPLICATION: keepalived
      VERSION: ${{ vars.KEEPALIVED_VERSION }}
      PUSH_TO_PUBLIC: true
      PUSH_TO_PRIVATE: true
      WF_OWNER: ${{ vars.OWNER }}
      WF_REGISTRY_PRIVATE: ${{ vars.REGISTRY_PRIVATE }}
      WF_REGISTRY_PRIVATE_PULL: ${{ vars.REGISTRY_PRIVATE_PULL }}
      WF_REGISTRY_PUBLIC: ${{ vars.REGISTRY_PUBLIC }}
    secrets:
      WF_REGISTRY_PRIVATE_USER: ${{ secrets.REGISTRY_PRIVATE_USER01 }}
      WF_REGISTRY_PRIVATE_PASSWD: "${{ secrets.REGISTRY_PRIVATE_USER01_PASSWD }}"
      WF_REGISTRY_PUBLIC_USER: ${{ github.actor }}
      WF_REGISTRY_PUBLIC_PASSWD: ${{ secrets.PAT_PACKAGES }}
